version: '3.4'

networks:
  dev:
    driver: bridge

services:
  subsetsix_api:
    image: ${DOCKER_REGISTRY-}subsetsixapi
    container_name: "subsetsix-api"
    depends_on:
      - "subsetsix_db"
    build:
      context: .
      dockerfile: src/Subsetsix.Api/Dockerfile
    ports:
      - "54233:8080"
      - "54234:8081"

  subsetsix_db:
    image: postgres:latest
    container_name: "subsetsix-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=subsetsix
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
