version: '3.4'

services:
  subsetsix.api:
    image: ${DOCKER_REGISTRY-}subsetsixapi
    container_name: "subsetsix.api"
    depends_on:
      - "subsetsix.db"
    build:
      context: .
      dockerfile: src/Subsetsix.Api/Dockerfile
    ports:
      - "54233:8080"
      - "54234:8081"

  subsetsix.db:
    image: postgres:latest
    container_name: "subsetsix.db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=subsetsix
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/subsetsix-db:/var/lib/postgresql/data
