@BaseUrl = http://localhost:5167

###

GET {{BaseUrl}}/health

###

GET {{BaseUrl}}/items.list
Accept: application/json

###

POST {{BaseUrl}}/items.add
Content-Type: application/json

{
  "title": "Item {{$timestamp}}",
  "description": "Description {{$timestamp}}",
  "tags": ["projects\\aws", "system\\pinned"]
}

###
